<?php

/**
 * @file
 * Contains install and update for Vardoc profile module.
 */

use Drupal\user\Entity\User;
use Vardot\Entity\EntityDefinitionUpdateManager;
use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Recipe\Recipe;
use Drupal\Core\Recipe\RecipeRunner;

/**
 * Implements hook_install().
 */
function vardoc_profile_install() {

  $default_recipe = Recipe::createFromDirectory(__DIR__ . '/recipes/default');
  RecipeRunner::processRecipe($default_recipe);

  // Load the user 1 to fill in first name, last name, and profile image
  $user = User::load(1);
  $user->set('field_first_name', 'Vardoc')
    ->set('field_last_name', 'Webmaster');

  // Create avatar file entity.
  $data = file_get_contents(\Drupal::service('extension.path.resolver')->getPath('module', 'vardoc_profile') . '/images/avatar.png');
  $file = \Drupal::service('file.repository')->writeData($data, 'public://avatar.png', FileSystemInterface::EXISTS_REPLACE);
  // Attach the file into user profile image and then save it.
  $user->field_profile_image->setValue(['target_id' => $file->id()]);
  $user->save();

  // Entity updates to clear up any mismatched entity and/or field definitions
  // And Fix changes were detected in the entity type and field definitions.
  \Drupal::classResolver()
    ->getInstanceFromDefinition(EntityDefinitionUpdateManager::class)
    ->applyUpdates();

}
