<?php
/**
 * @file
 * Install, update and uninstall functions for the Varbase installation profile.
 */

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;
use Drupal\shortcut\Entity\Shortcut;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function varbase_subprofile_basic_install() {
  include_once \Drupal::root() . '/profiles/varbase/varbase.install';

  varbase_install();
}
