<?php
/**
 * @file
 * Install, update and uninstall functions for the Vardoc installation profile.
 */

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;
use Drupal\shortcut\Entity\Shortcut;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function vardoc_install() {
  include_once drupal_get_path('profile', 'varbase') . '/varbase.install';
  varbase_install();
}
