name: Vardoc Basic Page - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - varbase_core
  - varbase_media
  - varbase_seo
  - vardoc_book
  - rdf
  - menu_ui
  - page_manager
config:
  strict: false
  actions:
    user.role.editor:
      grantPermissions:
        - 'create page content'
        - 'delete own page content'
        - 'edit own page content'
        - 'translate page node'
        - 'view page revisions'
    user.role.seo_admin:
      grantPermissions:
        - 'create page content'
        - 'delete own page content'
        - 'edit own page content'
        - 'translate page node'
        - 'view page revisions'
    user.role.content_admin:
      grantPermissions:
        - 'create page content'
        - 'delete own page content'
        - 'edit own page content'
        - 'translate page node'
        - 'view page revisions'
        - 'delete any page content'
        - 'clone page entity'
        - 'clone page_variant entity'
        - 'delete page revisions'
        - 'edit any page content'
        - 'revert page revisions'
        - 'view page revisions'
    user.role.site_admin:
      grantPermissions:
        - 'create page content'
        - 'delete own page content'
        - 'edit own page content'
        - 'translate page node'
        - 'view page revisions'
        - 'delete any page content'
        - 'clone page entity'
        - 'clone page_variant entity'
        - 'delete page revisions'
        - 'edit any page content'
        - 'revert page revisions'
        - 'view page revisions'
