name: Vardoc Search - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - vardoc_book
  - search_api
  - search_api_db
  - search_api_autocomplete
config:
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'use search_api_autocomplete for book_search'
    user.role.authenticated:
      grantPermissions:
        - 'use search_api_autocomplete for book_search'

