<?php

/**
 * @file
 * Vardoc Book enhancements.
 */

/**
 * Implements hook_editor_js_settings_alter().
 */
function vardoc_book_editor_js_settings_alter(array &$settings) {
  // Add BG color WYSIWYG style with enhancements.
  $extra_editor_settings = [
    'colorButton_backStyle' => [
    'element' => 'span',
      'attributes' => ['style' => 'background-color:#(color);', 'class' => 'text-with-bg']
    ]
  ];
  $settings['editor']['formats']['full_html']['editorSettings'] += $extra_editor_settings;
}
