<?php

/**
 * @file
 * Vardoc Book enhancements.
 */

/**
 * Implements hook_editor_js_settings_alter().
 */
function vardoc_book_editor_js_settings_alter(array &$settings) {

  if (isset($settings['editor']['formats']['full_html'])
    && array_key_exists('editorSettings', $settings['editor']['formats']['full_html'])
    && is_array($settings['editor']['formats']['full_html']['editorSettings'])) {

    // Add BG color WYSIWYG style with enhancements.
    $settings['editor']['formats']['full_html']['editorSettings']['colorButton_backStyle'] = [
      'element' => 'span',
      'attributes' => ['style' => 'background-color:#(color);', 'class' => 'text-with-bg'],
    ];
  }
}
