name: Vardoc Homepage - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - varbase_core
  - varbase_media
  - varbase_webform
  - entityqueue
  - page_manager
  - panels
  - vardoc_book
  - vardoc_tools
  - vardoc_search
config:
  actions:
    views.view.frontpage:
      simpleConfigUpdate:
        status: false
