name: Vardoc Book - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - comment
  - book
  - statistics
  - flag
  - sharethis
  - votingapi_widgets
  - page_manager
  - panels
config:
  import:
    book: '*'
    comment: '*'
    statistics: '*'
    flag: '*'
    sharethis: '*'
    votingapi_widgets: '*'
    page_manager: '*'
    panels: '*'
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'vote on node:book:field_rating'
        - 'edit own vote on node:book:field_rating'
        - 'access comments'
        - 'post comments'
        - 'view post access counter'
        - 'edit own comments'
    user.role.authenticated:
      grantPermissions:
        - 'create new books'
        - 'add content to books'
        - 'create book content'
        - 'delete own book content'
        - 'edit own book content'
        - 'vote on node:book:field_rating'
        - 'edit own vote on node:book:field_rating'
        - 'view book revisions'
        - 'access comments'
        - 'post comments'
        - 'view post access counter'
    user.role.editor:
      grantPermissions:
        - 'edit any book content'
        - 'administer book outlines'
    user.role.seo_admin:
      grantPermissions:
        - 'edit any book content'
        - 'administer book outlines'
    user.role.content_admin:
      grantPermissions:
        - 'edit any book content'
        - 'administer book outlines'
        - 'skip comment approval'
    user.role.site_admin:
      grantPermissions:
        - 'edit any book content'
        - 'clear own vote on node:book:field_rating'
        - 'edit voting status on node:book:field_rating'
        - 'delete book revisions'
        - 'revert book revisions'
        - 'delete any book content'
        - 'administer book outlines'
        - 'create terms in category'
        - 'view terms in category'
        - 'delete terms in category'
        - 'skip comment approval'
